### ISSUE TITLE
Stock history DB seed

### ISSUE THREAD

**Issue by wmantly** [himleyb85/recession_survivor#92]
We need to seed the database with stock data history. It needs to have as many fields as possible, such as, Symbol, Date, price, volume. There is a model in portfolio/models.py that i started, please use that and extend it as needed.

The pioneers need basically the same data for there final project, we can use what they did as reference;
https://github.com/lucasbrambrink/trading/tree/master/data_source

**Comment by himleyb85** [comment]
right now the seed.py file loads about 25 stocks, then fails on CAG:
django.db.utils.IntegrityError: null value in column "open_price" violates not-null constraint
DETAIL:  Failing row contains (37720, CAG, 2012-10-29, null, null, null, null, 0, 0.25, null).

Also, the GOOG stocks are only importing since the stock split in march 2014, we need the ealier prices as well
